### ISSUE TITLE
可以看到此时有一个主分区，一个扩展分区，剩下只能分两个逻辑分区

### ISSUE THREAD

**Issue by fengliebing** [jeffacode/Learning-Linux#1]
这句话不对，MBR分区支持4个主分区或3个主分区，一个扩展分区

此时有一个主分区，一个扩展分区，剩下只能分两个主分区

逻辑分区:
SCSI 最多 16 个
IDE 最多 63 个

**Comment by jeffacode** [comment]
不好意思啊，这两天做毕业设计没来得及看。我回过去看了下视频，你说的对的，4个主分区最多只能拿一个出来作为扩展分区。在视频里，老师在那块硬盘上分了一个3000MB的主分区后把剩下所有的磁盘空间都分给了一个扩展分区，然后再在这个扩展分区上分了两个逻辑分区。
